build release

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -41,38 +41,37 @@ jobs:
     - name: Tag release
       run: git tag $TAG
 
-#    - name: Push Tag
-#      env:
-#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#      run: |
-#
-#        # get current commit hash
-#        commit=$(git rev-parse HEAD)
-#
-#        # push new tag ref to github
-#        dt=$(date '+%Y-%m-%dT%H:%M:%SZ')
-#        full_name=$GITHUB_REPOSITORY
-#        git_refs_url=$(jq .repository.git_refs_url $GITHUB_EVENT_PATH | tr -d '"' | sed 's/{\/sha}//g')
-#
-#        echo "$dt: **pushing tag $TAG to repo $full_name"
-#
-#        git_refs_response=$(
-#        curl -s -X POST $git_refs_url \
-#        -H "Authorization: token $GITHUB_TOKEN" \
-#        -d @- << EOF
-#        {
-#          "ref": "refs/tags/$TAG",
-#          "sha": "$commit"
-#        }
-#        EOF
-#        )
-#
-#        git_ref_posted=$( echo "${git_refs_response}" | jq .ref | tr -d '"' )
-#
-#        echo "::debug::${git_refs_response}"
-#        if [ "${git_ref_posted}" = "refs/tags/${TAG}" ]; then
-#          exit 0
-#        else
-#          echo "::error::Tag was not created properly."
-#          exit 1
-#        fi
+    - name: Push Tag
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        # get current commit hash
+        commit=$(git rev-parse HEAD)
+
+        # push new tag ref to github
+        dt=$(date '+%Y-%m-%dT%H:%M:%SZ')
+        full_name=$GITHUB_REPOSITORY
+        git_refs_url=$(jq .repository.git_refs_url $GITHUB_EVENT_PATH | tr -d '"' | sed 's/{\/sha}//g')
+
+        echo "$dt: **pushing tag $TAG to repo $full_name"
+
+        git_refs_response=$(
+        curl -s -X POST $git_refs_url \
+        -H "Authorization: token $GITHUB_TOKEN" \
+        -d @- << EOF
+        {
+          "ref": "refs/tags/$TAG",
+          "sha": "$commit"
+        }
+        EOF
+        )
+
+        git_ref_posted=$( echo "${git_refs_response}" | jq .ref | tr -d '"' )
+
+        echo "::debug::${git_refs_response}"
+        if [ "${git_ref_posted}" = "refs/tags/${TAG}" ]; then
+          exit 0
+        else
+          echo "::error::Tag was not created properly."
+          exit 1
+        fi
